[package]
name = "farcaster-core"
version = "0.1.0"
authors = ["h4sh3d <h4sh3d@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.26.0"
hex = "0.4.3"
monero = "0.10.0"
secp256k1 = { version = "0.20.1", features = ["rand-std"] }
curve25519-dalek = "3.0.0"
rand_core = { version = "^0.5.0", features = ["getrandom"] }
thiserror = "1.0.24"

# monero = "0.10.0"
monero = { git = "https://github.com/monero-rs/monero-rs", branch = "master"}

# node
# lnpbp = { git = "https://github.com/zkao/rust-lnpbp.git", branch = "farcaster_encoding" }
strict_encoding = { path = "../alt/rust-lnpbp/strict_encoding" }

[dev-dependencies]
bitcoincore-rpc = "0.13.0"
