name: Release to crates.io

on:
  release:
    types: [ created ]

jobs:
  release:
    name: "Publish the new release to crates.io"
    uses: farcaster-project/workflows/.github/workflows/release-to-crates-io.yml@v1.0.0
    secrets:
      cratesio_token: ${{ secrets.H4SH3D_CARGO_REGISTRY_TOKEN }}
